#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
pgrep bspswallow || bspswallow &
killall polybar; polybar bar &

bspc monitor -d 1 2 3 4 5 6 7 8 9


bspc config focused_border_color '#4c7bab'
bspc config normal_border_color '#222222'
bspc config active_border_color '#222222'
bspc config window_gap 0 
bspc config border_width         3
bspc config split_ratio          0.5
bspc config focus_follows_pointer true
