# PLACEHOLDER — regenerate on the machine after installing.
#
# `nixos-generate-config` does not produce a usable config on Snapdragon X
# devices (see kuruczgy/x1e-nixos-config); write this by hand from the actual
# disk layout. The UUIDs below are fictional — the system will not boot until
# they match the real partitions. Layout mirrors jane-laptop: btrfs root on a
# LUKS container ("cryptroot", FIDO2-unlocked) + vfat ESP at /boot.

# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "nvme"
    "usb_storage"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/CHANGE_ME_ROOT";
    fsType = "btrfs";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/CHANGE_ME_EFI";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  fileSystems."/home" = {
    device = "/dev/mapper/cryptroot";
    fsType = "btrfs";
  };

  boot.initrd.luks.devices."cryptroot".device = "/dev/disk/by-uuid/CHANGE_ME_LUKS";

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "aarch64-linux";
}
